name: WebdriverIO Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v4

        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            node-version: '20'

        - name: Install Dependencies
          run: npm install

        - name: Test
          run: npm run wdio
          continue-on-error: true

        - name: Install Allure CLI
          run: |
            curl -o allure-2.24.1.tgz -Ls https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
            tar -zxvf allure-2.24.1.tgz -C /opt/
            ln -s /opt/allure-2.24.1/bin/allure /usr/local/bin/allure

        - name: Generate report
          run: allure generate --clean allure-results

        - name: Upload Reports
          uses: actions/upload-artifact@v4
          with:
            name: allure-reports
            path: allure-report 